name: Check JMeter Listeners

on:
  push:
    branches:
      - '*'
  
jobs:
  check_listeners:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.x'

   # Run the Python script to check if listeners are disabled in all .jmx files
    - name: Check JMeter Listeners
      run: |
        python check_listeners.py
      env:
        JMX_DIR: '.'
